pipeline {
	agent {
		label 'gba'
	}
	stages {
		stage('Environment') {
			steps {
				load 'jenkins/shared/env.gy'
				sh 'make conan-config'
				sh 'make conan'
			}
		}
		stage('Build Tools Debug') {
			steps {
				sh 'make purge configure-debug'
				sh 'make install'
			}
		}
		stage('Build GBA Debug') {
			steps {
				sh 'make configure-gba-debug'
				sh 'make'
				sh 'make pkg-gba'
			}
		}
		stage('Build Tools Release') {
			steps {
				sh 'make purge configure-release'
				sh 'make install'
			}
		}
		stage('Build GBA Release') {
			steps {
				sh 'make configure-gba'
				sh 'make'
				sh 'make pkg-gba'
			}
		}
	}
	post {
		always {
			archiveArtifacts artifacts: 'nostalgia.gba', fingerprint: true
		}
	}
}
