pipeline {
	agent {
		label 'gba'
	}
	environment {
		DEVKITPRO = '/opt/devkitpro'
		DEVKITARM = '/opt/devkitpro/devkitARM'
		VCPKG_DIR_BASE = '/var/lib/vcpkg/nostalgia/'
	}
	stages {
		stage('Environment') {
			steps {
				sh 'make vcpkg'
			}
		}
		stage('Build Tools Debug') {
			steps {
				sh 'make purge configure-debug'
				sh 'make install'
			}
		}
		stage('Build GBA Debug') {
			steps {
				sh 'make configure-gba-debug'
				sh 'make'
				sh 'make pkg-gba'
			}
		}
		stage('Build Tools Release') {
			steps {
				sh 'make purge configure-release'
				sh 'make install'
			}
		}
		stage('Build GBA Release') {
			steps {
				sh 'make configure-gba'
				sh 'make'
				sh 'make pkg-gba'
			}
		}
	}
	post {
		always {
			archiveArtifacts artifacts: 'nostalgia.gba', fingerprint: true
		}
	}
}
