#! /usr/bin/env bash

set -e

BIN=./dist/current/bin/
PATH=$BIN:${DEVKITARM}/bin/:$PATH
NOSTALGA_BIN=build/gba-*/src/nostalgia/player/nostalgia.bin
NOSTALGA_MEDIA=nostalgia_media.oxfs
NOSTALGA_GBA=nostalgia.gba
MEDIA_HEADER=media_header.txt
CHARSET_FILE=src/nostalgia/core/studio/charset.png
TILESHEET_TEST_REGION1=media/tilesheet_test_region1.png

echo NOSTALGIA_MEDIA_HEADER_________ > $MEDIA_HEADER

oxfs format 32 1k $NOSTALGA_MEDIA
nost-pack -fs $NOSTALGA_MEDIA -img $CHARSET_FILE           -inode 101 -tiles 127 -bpp 4 -c
nost-pack -fs $NOSTALGA_MEDIA -img $TILESHEET_TEST_REGION1 -inode 102 -tiles 4 -bpp 4 -c

padbin 32 $NOSTALGA_BIN
cat $NOSTALGA_BIN $MEDIA_HEADER $NOSTALGA_MEDIA > $NOSTALGA_GBA
rm -f $MEDIA_HEADER $NOSTALGA_MEDIA
gbafix $NOSTALGA_GBA
