#! /usr/bin/env bash

set -e

project=$(pwd)/

TARGET=$1
BUILD_TYPE=$2

if [[ $TARGET == windows ]]; then
	toolchain="-DCMAKE_TOOLCHAIN_FILE=cmake/Modules/Mingw.cmake"
elif [[ $TARGET == gba ]]; then
	toolchain="-DCMAKE_TOOLCHAIN_FILE=cmake/Modules/GBA.cmake -DWOMBAT_BUILD_TYPE=GBA -DOX_USE_STDLIB=OFF -DCMAKE_INSTALL_PREFIX=$DEVKITARM"
fi

if [[ $BUILD_TYPE == debug ]]; then
	buildTypeArgs="-DUSE_ASAN=ON -DCMAKE_BUILD_TYPE=Debug"
elif [[ $BUILD_TYPE == release ]]; then
	buildTypeArgs="-DCMAKE_BUILD_TYPE=Release"
fi

buildDir="build/${TARGET}-${BUILD_TYPE}"
distDir="../../dist/${TARGET}-${BUILD_TYPE}"

mkdir -p $buildDir
pushd $buildDir
cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_INSTALL_PREFIX="$distDir" \
      $buildTypeArgs \
      $toolchain \
      $project
popd
