pipeline {
	agent {
		label params.Platform
	}
	stages {
		stage('Environment') {
			steps {
				load 'jenkins/shared/env.gy'
				sh 'make vcpkg'
			}
		}
		parallel {
			stage ('Asan') {
				stage('Build Asan') {
					steps {
						sh 'make purge configure-asan'
						sh 'make'
					}
				}
				stage('Test Asan') {
					steps {
						sh 'make test'
					}
				}
			}
			stage ('Debug') {
				stage('Build Debug') {
					steps {
						sh 'make purge configure-debug'
						sh 'make'
					}
				}
				stage('Test Debug') {
					steps {
						sh 'make test'
					}
				}
			}
			stage ('Release') {
				stage('Build Release') {
					steps {
						sh 'make purge configure-release'
						sh 'make'
					}
				}
				stage('Test Release') {
					steps {
						sh 'make test'
					}
				}
			}
		}
	}
}
